### PR TITLE
Change PostgreSQLContainer wait behaviour (fix #317)

### LINKED ISSUE #317: Postgres JDBC 42.0.0 produces tons of error logs on container startup
```
2017-03-24 18:56:50.647 ERROR --- [      pool-3-thread-2] o.p.Driver                               : Connection error: 
org.postgresql.util.PSQLException: The connection attempt failed.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:275) ~[postgresql-42.0.0.jar:42.0.0]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49) ~[postgresql-42.0.0.jar:42.0.0]
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:194) ~[postgresql-42.0.0.jar:42.0.0]
	at org.postgresql.Driver.makeConnection(Driver.java:431) ~[postgresql-42.0.0.jar:42.0.0]
	at org.postgresql.Driver.connect(Driver.java:247) ~[postgresql-42.0.0.jar:42.0.0]
	at org.testcontainers.containers.JdbcDatabaseContainer.lambda$createConnection$2(JdbcDatabaseContainer.java:123) ~[jdbc-1.2.0.jar:?]
	at org.rnorth.ducttape.unreliables.Unreliables.lambda$retryUntilSuccess$0(Unreliables.java:41) ~[duct-tape-1.0.6.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.io.EOFException
	at org.postgresql.core.PGStream.receiveChar(PGStream.java:284) ~[postgresql-42.0.0.jar:42.0.0]
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:418) ~[postgresql-42.0.0.jar:42.0.0]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:222) ~[postgresql-42.0.0.jar:42.0.0]
	... 10 more
```
With `9.4.1212` they are produced as well, but not logged.

Probably this change made them appear by default with some logging configurations:
https://www.postgresql.org/about/news/1736/
> java.util.logging is now used for logging: logging documentation

Is it something that could be fixed on your side or I should just disable all logging for PG driver?
Feels, like a bad idea...

### PR DESCRIPTION
**Pull request by kiview**
I've changed the `PostgreSQLContainer` to use the `WaitingConsumer` for waiting for Log output, instead of performing SQL queries. It's basically the same code as in `LogWaitStrategy`, but I've figured we'll refactor the `JdbcDatabaseContainers` at a later stage, to make use of a `WaitingStrategy`?

This fixes #317

### CODE REVIEW

File: modules/postgresql/src/main/java/org/testcontainers/containers/PostgreSQLContainer.java [hunk 1]
```diff
@@ -73,4 +80,23 @@ public SELF withPassword(final String password) {
...
+    protected void waitUntilContainerStarted() {
+        String regEx = ".*database system is ready to accept connections.*\\s";
+        logger().info("Waiting for database to log '{}'", regEx);
+
+        WaitingConsumer waitingConsumer = new WaitingConsumer();
+        this.followOutput(waitingConsumer);
+
+
+        Predicate<OutputFrame> waitPredicate = outputFrame ->
+                outputFrame.getUtf8String().matches(regEx);
```
Comment (dbyron0) [inline modules/postgresql/src/main/java/org/testcontainers/containers/PostgreSQLContainer.java]: This is an out of the way way to mention this, but I've had this kind of code throw a NullPointerException when the regEx doesn't match any output.  Pretty sure it's because getUtf8String [returns null](https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/containers/output/OutputFrame.java#L33).  I don't see the harm in having that return an empty string instead of null, but haven't tested it.  With the code the way it is, I think we could use a null check here.

Comment (kiview) [inline modules/postgresql/src/main/java/org/testcontainers/containers/PostgreSQLContainer.java]: Good point, this means we should fix this in `LogMessageWaitStrategy` as well I assume?
https://github.com/testcontainers/testcontainers-java/blob/c2eae85232653273748aaa4f5f765f48c28e0f87/core/src/main/java/org/testcontainers/containers/wait/LogMessageWaitStrategy.java#L25

Comment (dbyron0) [inline modules/postgresql/src/main/java/org/testcontainers/containers/PostgreSQLContainer.java]: Yeah, I'd prefer having getUtf8String return an empty string too.  Otherwise I think we end up with null checks in all kinds of places, like https://github.com/testcontainers/testcontainers-java/blob/master/docs/usage/options.md#waiting-for-container-output-to-contain-expected-content.

Comment (rnorth) [inline modules/postgresql/src/main/java/org/testcontainers/containers/PostgreSQLContainer.java]: Yes, that sounds like a good idea - thanks.

Comment (rnorth) [inline modules/postgresql/src/main/java/org/testcontainers/containers/PostgreSQLContainer.java]: I've had a look - I can't see how `ToStringConsumer` could return null though. It uses:
```java
        byte[] bytes = stringBuffer.toByteArray();
        return new String(bytes, Charsets.UTF_8);
```
If `stringBuffer` is empty, `bytes` becomes an empty byte array. `new String(...)` does create an empty String (not null) if passed a zero-length byte array.

Have I missed something?

Comment (dbyron0) [inline modules/postgresql/src/main/java/org/testcontainers/containers/PostgreSQLContainer.java]: We're talking about OutputFrame::getUtf8String, not ToStringConsumer::getUtf8String...

Comment (rnorth) [inline modules/postgresql/src/main/java/org/testcontainers/containers/PostgreSQLContainer.java]: Ah, sorry!

Comment (kiview) [inline modules/postgresql/src/main/java/org/testcontainers/containers/PostgreSQLContainer.java]: I've added the change in this PR.
Can someone with write access please retry the TravisCI build? The same build was green in my branch, so I think this might have been some problem with Travis or Docker in the build.

**Comment by kiview** [comment]
@rnorth Since you're already performing a refactoring of the Browser containers to use `WaitStrategy` in this [PR](https://github.com/testcontainers/testcontainers-java/pull/328#discussion_r111680340), should I refactor this implementation to also rely on a `WaitStrategy`?

**Comment by kiview** [comment]
Using `LogMessageWaitStratgy` works great, I wonder if `PostgreSQLContainer` still needs to extend `JdbcDatabaseContainer` now?

**Comment by rnorth** [comment]
@kiview that's a good point - would be interesting if we can break the inheritance hierarchy. @asafm  has kinda persuaded me to give that approach a chance :)

That said, it's not that easy to put the genie back in the bottle - we'd just need to consider whether this would cause any breaking changes (e.g. people using `PostgresContainer` and using methods that might cease to exist on its public API, like mounting volumes, etc).

I think it would be worth considering that as a separate change from this PR. I am, in general, meaning to kick off conversations about what the next iteration of the API will look like soon, so it's something we could consider at that stage.

**Comment by kiview** [comment]
@rnorth I'd also like to perform this refactoring in a seperate PR.

Regarding the failing codacy check:
I'm personally fine with using package scoping, if package scoping is all that's needed. I can however of course change the constants back to public scoping if you prefer it that way.

**Comment by rnorth** [comment]
This looks good to me - no worries about the codacy warning; that's for guidance only and I agree with you on it.
Will merge!
