### PR TITLE
VNC recording with BrowserWebdriverContainer in Spock-Extension

### LINKED ISSUE #631: Spock extension does not create video recordings of failed BrowserWebDriverContainer tests
`BrowserWebDriverContainer` leverages JUnit's `failed()` and `succeeded()` callbacks. These methods are not called if used with the Spock extension.

### PR DESCRIPTION
**Pull request by kiview**
Revives #726.

Initially done as part of the Hackergarten at Gr8ConfEU 2018 (yes, that long ago :sweat_smile:).
Thanks to Tamer Shahin, Marcin Erdmann and Dawid Kublik for working on this :slightly_smiling_face:  !

Fixes #631.

### CODE REVIEW

**Comment by kiview** [comment]
Thinking about it, this is probably missing support for `@Shared` containers as of now, but we can add this in a later stage.

File: modules/spock/src/main/groovy/org/testcontainers/spock/SpockTestDescription.groovy [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+    }
+
+    @Override
+    String getTestId() {
+        return null
+    }
+
+    @Override
+    String getFilesystemFriendlyName() {
+        return [specName, featureName].collect {
```
Comment (bsideup) [inline modules/spock/src/main/groovy/org/testcontainers/spock/SpockTestDescription.groovy:32]: AFAIK `specName` can be an arbitrary string. Perhaps we should encode it (similar to #1326)

File: modules/spock/src/main/groovy/org/testcontainers/spock/SpockTestDescription.groovy [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+    static SpockTestDescription fromTestDescription(IMethodInvocation invocation) {
+        return new SpockTestDescription([
+            specName: invocation.spec.name,
+            featureName: invocation.feature.name
+        ])
+    }
+
+    @Override
+    String getTestId() {
+        return null
```
Comment (bsideup) [inline modules/spock/src/main/groovy/org/testcontainers/spock/SpockTestDescription.groovy:27]: huh?

File: modules/spock/src/main/groovy/org/testcontainers/spock/TestcontainersExtension.groovy [hunk 3]
```diff
@@ -1,17 +1,32 @@
...
         spec.addSetupSpecInterceptor(interceptor)
         spec.addCleanupSpecInterceptor(interceptor)
         spec.addSetupInterceptor(interceptor)
         spec.addCleanupInterceptor(interceptor)
+
+        spec.addListener(listener)
+
+    }
+
+    class ErrorListener extends AbstractRunListener {
```
Comment (bsideup) [inline modules/spock/src/main/groovy/org/testcontainers/spock/TestcontainersExtension.groovy:23]: private?

File: modules/spock/src/test/groovy/org/testcontainers/spock/BrowserVncRecordingIT.groovy [hunk 4]
```diff
@@ -0,0 +1,176 @@
...
+
+    def setup() {
+        recordingDir = temp.getRoot().getAbsolutePath()
+    }
+
+    def "retains all recordings for RECORD_ALL if successful"() {
+        given:
+
+        //noinspection GrPackage
+        @Language("groovy")
```
Comment (bsideup) [inline modules/spock/src/test/groovy/org/testcontainers/spock/BrowserVncRecordingIT.groovy:24]: TIL! Cool :)

File: modules/spock/src/main/groovy/org/testcontainers/spock/SpockTestDescription.groovy [hunk 5]
```diff
@@ -0,0 +1,36 @@
...
+@PackageScope
+class SpockTestDescription implements TestDescription {
+
+    String specName
+    String featureName
+
+    static SpockTestDescription fromTestDescription(IMethodInvocation invocation) {
+        return new SpockTestDescription([
+            specName: invocation.spec.name,
+            featureName: invocation.feature.name
```
Comment (bsideup) [inline modules/spock/src/main/groovy/org/testcontainers/spock/SpockTestDescription.groovy:21]: FYI `invocation.feature` is marked as `@Nullable`

Comment (bsideup) [reply modules/spock/src/main/groovy/org/testcontainers/spock/SpockTestDescription.groovy:21]: probably `getMethod()` is more appropriate here?

File: modules/spock/src/main/groovy/org/testcontainers/spock/SpockTestDescription.groovy (hunk 1 above)
Comment (kiview) [reply modules/spock/src/main/groovy/org/testcontainers/spock/SpockTestDescription.groovy:32]: Yes, both actually (since Groovy method names can be arbitrary Strings?).

File: modules/spock/src/main/groovy/org/testcontainers/spock/SpockTestDescription.groovy (hunk 2 above)
Comment (kiview) [reply modules/spock/src/main/groovy/org/testcontainers/spock/SpockTestDescription.groovy:27]: This method is used nowhere, TBH I don't even understand why we have it in our interface and assumed it to come from refactoring from original JUnit test description.

File: modules/spock/src/main/groovy/org/testcontainers/spock/TestcontainersExtension.groovy (hunk 3 above)
Comment (kiview) [reply modules/spock/src/main/groovy/org/testcontainers/spock/TestcontainersExtension.groovy:23]: sure

File: modules/spock/src/main/groovy/org/testcontainers/spock/SpockTestDescription.groovy (hunk 5 above)
Comment (kiview) [reply modules/spock/src/main/groovy/org/testcontainers/spock/SpockTestDescription.groovy:21]: k, will check in the implementation.

Comment (kiview) [reply modules/spock/src/main/groovy/org/testcontainers/spock/SpockTestDescription.groovy:21]: Actually I don't understand the null condition from the javadoc:
```
   * Returns the feature which this method invocation belongs to (if any).
   * Differs from {@code MethodInfo.getFeature()} in that it reflects the dynamic
   * picture. For example, when a setup method is invoked, this method
   * will return the corresponding feature, whereas {@code MethodInfo.getFeature()}
   * will return {@code null}.
```

Comment (kiview) [reply modules/spock/src/main/groovy/org/testcontainers/spock/SpockTestDescription.groovy:21]: So if potentially called from within a `setup` block, we would still get the actual feature name, which is good IMO.

So TBH, I'd prefer to keep feature how, although I still wonder how it might be `nullabe`.

Comment (kiview) [reply modules/spock/src/main/groovy/org/testcontainers/spock/SpockTestDescription.groovy:21]: So FY, in the context of our extension execution `getMethod()` is actually `null`, so let's keep like this for now :man_shrugging:

Comment (bsideup) [reply modules/spock/src/main/groovy/org/testcontainers/spock/SpockTestDescription.groovy:21]: Ok, I trust you here :)

File: modules/spock/src/main/groovy/org/testcontainers/spock/SpockTestDescription.groovy (hunk 2 above)
Comment (bsideup) [reply modules/spock/src/main/groovy/org/testcontainers/spock/SpockTestDescription.groovy:27]: we could/should deprecate it, but let's not return `null` here anyways.

File: modules/spock/src/test/groovy/org/testcontainers/spock/BrowserVncRecordingIT.groovy [hunk 6]
```diff
@@ -0,0 +1,176 @@
...
+    @Rule
+    TemporaryFolder temp
+
+    String recordingDir
+
+    def setup() {
+        recordingDir = temp.getRoot().getAbsolutePath()
+    }
+
+    def "retains all recordings for RECORD_ALL if successful"() {
```
Comment (bsideup) [inline modules/spock/src/test/groovy/org/testcontainers/spock/BrowserVncRecordingIT.groovy:20]: would be cool to parameterize these 3 tests into something like:
```groovy
| mode | fails | files |
| RECORD_ALL | false | BrowserWebdriverContainerIT-should+record |
| RECORD_FAILING | false | |
| RECORD_FAILING | true | BrowserWebdriverContainerIT-should+record |
```

Comment (kiview) [reply modules/spock/src/test/groovy/org/testcontainers/spock/BrowserVncRecordingIT.groovy:20]: yes cool, I try

File: modules/spock/src/main/groovy/org/testcontainers/spock/SpockTestDescription.groovy (hunk 2 above)
Comment (kiview) [reply modules/spock/src/main/groovy/org/testcontainers/spock/SpockTestDescription.groovy:27]: What is semantically correct here then? Same then filesystemFriendly name?

Comment (bsideup) [reply modules/spock/src/main/groovy/org/testcontainers/spock/SpockTestDescription.groovy:27]: should work, yes 👍

**Comment by rnorth** [comment]
This was released in https://github.com/testcontainers/testcontainers-java/releases/tag/1.14.0 🎉

Thanks for the contribution!
