### PR TITLE
Fix K3S start command

### LINKED ISSUE #6770: [Bug]: k3s > 1.24.x will not start
### Module

K3S

### Testcontainers version

1.17.6

### Using the latest Testcontainers version?

Yes

### Host OS

Ubuntu 20.04 on WSL2 on Windows 11

### Host Arch

x86

### Docker version

```shell
Client:
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.2
 Git commit:        20.10.12-0ubuntu2~20.04.1
 Built:             Wed Apr  6 02:14:38 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop
 Engine:
  Version:          20.10.23
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.10
  Git commit:       6051f14
  Built:            Thu Jan 19 17:32:04 2023
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

k3s testcontainer will not start. Log message: 
for k3s 1.25.x
```
no-deploy flag is deprecated. Use --disable instead.
```
for k3s 1.26.x
```
flag provided but not defined: -no-deploy
```

I traced it back to this line
https://github.com/testcontainers/testcontainers-java/blob/c90daab5d80adb692f213fa5f02c108a329105d5/modules/k3s/src/main/java/org/testcontainers/k3s/K3sContainer.java#L44

see also https://docs.k3s.io/reference/server-config#deprecated-options

Workaround is to use k3s<=1.24.x

### Relevant log output

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by tgeens**
This PR fixes #6770 by swapping the deprecated/removed `--no-deploy` flag with the replacement flag `--disable`

This change is backwards compatible and tested with a wide range of versions:
- oldest version succesfully tested: `rancher/k3s:v1.17.17-k3s1`
- current version (updated in tests): `rancher/k3s:v1.25.14-k3s1`

See:
- https://docs.k3s.io/cli/server#deprecated-options
- https://docs.k3s.io/installation/packaged-components#using-the---disable-flag

### CODE REVIEW

**Comment by eddumelendez** [comment]
Thanks for your contribution, @tgeens ! Can we add a test with `rancher/k3s:v1.17.17-k3s1` as a proof of being backward compatible, please?

File: modules/k3s/src/test/java/org/testcontainers/k3s/Fabric8K3sContainerTest.java [hunk 1]
```diff
@@ -26,9 +26,18 @@ public class Fabric8K3sContainerTest {
...
+    @Test
+    public void shouldStartAndHaveListableNode_backwardsCompat() {
+        runK3s(DockerImageName.parse("rancher/k3s:v1.17.17-k3s1"));
+    }
+
+    private void runK3s(DockerImageName k3sDockerImage) {
         try (
             // starting_k3s {
-            K3sContainer k3s = new K3sContainer(DockerImageName.parse("rancher/k3s:v1.21.3-k3s1"))
+            K3sContainer k3s = new K3sContainer(k3sDockerImage)
```
Comment (eddumelendez) [inline modules/k3s/src/test/java/org/testcontainers/k3s/Fabric8K3sContainerTest.java:40]: This change will break [the documentation](https://deploy-preview-7677--testcontainers.netlify.app/modules/k3s/#usage-example). We prefer to specify the image in this case. I think it will be totally fine to keep this test as is and the other one can be updated instead.

File: modules/k3s/src/test/java/org/testcontainers/k3s/OfficialClientK3sContainerTest.java [hunk 2]
```diff
@@ -20,9 +20,18 @@ public class OfficialClientK3sContainerTest {
 
     @Test
     public void shouldStartAndHaveListableNode() throws IOException, ApiException {
+        runK3s(DockerImageName.parse("rancher/k3s:v1.21.3-k3s1"));
+    }
+
+    @Test
+    public void shouldStartAndHaveListableNode_backwardsCompat() throws IOException, ApiException {
```
Comment (eddumelendez) [inline modules/k3s/src/test/java/org/testcontainers/k3s/OfficialClientK3sContainerTest.java:27]:
```suggestion
    public void shouldStartAndHaveListableNodeUsingLowerVersion() throws IOException, ApiException {
```

**Review by eddumelendez — COMMENTED** [review]
I've left a few comments/suggestions. After that I'll be merging the PR. Thanks again!.

**Review by eddumelendez — APPROVED** [review]

**Comment by eddumelendez** [comment]
Hi @tgeens, looks like the wait stragy fails using `rancher/k3s:v1.17.17-k3s1`. Can you take a look, please?

File: .github/workflows/ci.yml [hunk 3]
```diff
@@ -17,7 +17,7 @@ on:
       - 'RELEASING.md'
       - '.sdkmanrc'
   push:
-    branches: [ main ]
+    branches: [ main, k3s-disable-flag ]
```
Comment (eddumelendez) [inline .github/workflows/ci.yml:20]: this is not needed

File: modules/k3s/src/main/java/org/testcontainers/k3s/K3sContainer.java [hunk 4]
```diff
@@ -46,8 +47,12 @@ public K3sContainer(DockerImageName dockerImageName) {
         tmpFsMapping.put("/var/run", "");
         setTmpFsMapping(tmpFsMapping);
 
-        setCommand("server", "--no-deploy=traefik", "--tls-san=" + this.getHost());
-        setWaitStrategy(new LogMessageWaitStrategy().withRegEx(".*Node controller sync successful.*"));
+        setCommand("server", "--disable=traefik", "--tls-san=" + this.getHost());
+        setWaitStrategy(
+            new LogMessageWaitStrategy()
+                .withRegEx(".*Node controller sync successful.*")
+                .withStartupTimeout(Duration.ofMinutes(5))
```
Comment (eddumelendez) [inline modules/k3s/src/main/java/org/testcontainers/k3s/K3sContainer.java:54]: so, 5 min is required? The max should be 1 min for good experience.

**Review by eddumelendez — CHANGES_REQUESTED** [review]

File: modules/k3s/src/main/java/org/testcontainers/k3s/K3sContainer.java (hunk 4 above)
Comment (tgeens) [reply modules/k3s/src/main/java/org/testcontainers/k3s/K3sContainer.java:54]: Sorry, this were my own tests, I should have done these experiments on a separate branch, not on this PR.

I'm trying to figure out why local `./gradlew :k3s:test` works just fine locally, but not on GHA

**Comment by tgeens** [comment]
Before this PR, GHA builds/tests already fail for the following versions:
- `v1.17.17-k3s1`
- `v1.18.20-k3s1`
- `v1.19.16-k3s1`

Note that it works locally with `./gradlew test` just fine - and I could not figure out why.

The lowest minor version that succeeds with GHA builds is `v1.20.15-k3s1`

**Review by eddumelendez — APPROVED** [review]

**Comment by eddumelendez** [comment]
Thanks for the information, @tgeens! For me even locally fails with the versions you mentioned on M1. It would have been great to test against the minimal version but given our examples were using `rancher/k3s:v1.21.3-k3s1`, I'm ok with merging this.

**Comment by eddumelendez** [comment]
Thanks for your contribution, @tgeens ! This is now merged in `main` branch and it will be part of the next release.
