### PR TITLE
Ensure that ParsedDockerfile supports platform args

### LINKED ISSUE #2772: ParsedDockerfile's parsing of FROM lines doesn't handle arguments
Given a Dockerfile with a line like:

```
FROM --platform=linux/amd64 openjdk:8u252-jre
```

you will get warnings in the log that look like:

```
09:06:07.355 [tc-okhttp-stream-748761773] ERROR com.github.dockerjava.api.async.ResultCallbackTemplate - Error during callback
com.github.dockerjava.api.exception.BadRequestException: {"message":"invalid reference format"}

	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:283)
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.lambda$executeAndStream$4(OkHttpInvocationBuilder.java:317)
	at java.lang.Thread.run(Thread.java:748)
09:06:07.355 [main] WARN org.testcontainers.images.builder.ImageFromDockerfile - Unable to pre-fetch an image (--platform=linux/amd64) depended upon by Dockerfile - image build will continue but may fail. Exception message was: {"message":"invalid reference format"}
```

because ParsedDockerfile's regex doesn't handle parameters.

### PR DESCRIPTION
**Pull request by rnorth**
Fixes #2772

Also make parsing case insensitive, for better compliance with Dockerfile spec

### CODE REVIEW

File: core/src/test/java/org/testcontainers/images/ParsedDockerfileTest.java [hunk 1]
```diff
@@ -40,6 +46,12 @@ public void ignoringBuildStageNames() {
         assertEquals("ignores build stage names and allows multiple images to be extracted", Sets.newHashSet("someimage", "nextimage"), parsedDockerfile.getDependencyImageNames());
     }
 
+    @Test
+    public void ignoringPlatformArgs() {
+        final ParsedDockerfile parsedDockerfile = new ParsedDockerfile(asList("FROM --platform=linux/amd64 someimage", "RUN something"));
```
Comment (bsideup) [inline core/src/test/java/org/testcontainers/images/ParsedDockerfileTest.java:51]: since the parsing seem to support multiple flags, perhaps we should add this (2 or more flags) case too

Comment (rnorth) [reply core/src/test/java/org/testcontainers/images/ParsedDockerfileTest.java:51]: Platform seems to be the only arg that is supported by docker at present, but sure, seems like a good idea.
