### PR TITLE
Stabilize CouchbaseContainer by merging the Socat command

### LINKED ISSUE #1453: Intermittent couchbase failures in CI
For a long time we've been getting intermittent failures in CI, such as this:
```
shouldInsertDocument - org.testcontainers.couchbase.Couchbase4_6Test
com.couchbase.client.core.RequestCancelledException: Request cancelled in-flight.
	at com.couchbase.client.core.endpoint.AbstractGenericHandler.handleOutstandingOperations(AbstractGenericHandler.java:686)
	at com.couchbase.client.core.endpoint.AbstractGenericHandler.handlerRemoved(AbstractGenericHandler.java:667)
	at com.couchbase.client.deps.io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:626)
	at com.couchbase.client.deps.io.netty.channel.DefaultChannelPipeline.destroyDown(DefaultChannelPipeline.java:878)
	at com.couchbase.client.deps.io.netty.channel.DefaultChannelPipeline.destroyUp(DefaultChannelPipeline.java:844)
	at com.couchbase.client.deps.io.netty.channel.DefaultChannelPipeline.destroy(DefaultChannelPipeline.java:836)
	at com.couchbase.client.deps.io.netty.channel.DefaultChannelPipeline.access$700(DefaultChannelPipeline.java:44)
	at com.couchbase.client.deps.io.netty.channel.DefaultChannelPipeline$HeadContext.channelUnregistered(DefaultChannelPipeline.java:1286)
	at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:176)
	at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:162)
	at com.couchbase.client.deps.io.netty.channel.DefaultChannelPipeline.fireChannelUnregistered(DefaultChannelPipeline.java:821)
	at com.couchbase.client.deps.io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:776)
	at com.couchbase.client.deps.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:399)
	at com.couchbase.client.deps.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
	at com.couchbase.client.deps.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
	at com.couchbase.client.deps.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

Unfortunately this is a nuisance for us and for contributors. I've tried suggestions such as [this](https://stackoverflow.com/a/47049088/72305) but it hasn't improved reliability.

Can anyone with more Couchbase expertise help investigate?

To reproduce, run the test suites under `modules/couchbase` repeatedly.

### PR DESCRIPTION
**Pull request by bsideup**
Fixes #1453

### CODE REVIEW

File: modules/couchbase/src/main/java/org/testcontainers/couchbase/CouchbaseContainer.java [hunk 1]
```diff
@@ -150,18 +150,28 @@ private void startProxy(String networkAlias) {
...
+                            "TCP:" + networkAlias + ":" + getMappedPort(port);
+                    })
+                    .collect(Collectors.joining(" & ", "true", ""))
+            )
             .exec();
 
         dockerClient.execStartCmd(createCmdResponse.getId())
-            .exec(new ExecStartResultCallback());
+            .exec(new ExecStartResultCallback())
+            .awaitCompletion(10, TimeUnit.SECONDS);
```
Comment (bsideup) [inline modules/couchbase/src/main/java/org/testcontainers/couchbase/CouchbaseContainer.java]: FYI we were missing `awaitStarted` here, and I guess it caused some races

Comment (kiview) [reply modules/couchbase/src/main/java/org/testcontainers/couchbase/CouchbaseContainer.java]: Good catch!

**Comment by rnorth** [comment]
Nice! Absence of this looks like a bug, so let's merge it.

I'm running a soak test for this change and will report back this evening. Fingers crossed! 🤞
