### PR TITLE
Prevent Compose image pre-fetching from pulling all tags when tag is absent

### LINKED ISSUE #3442: DockerComposeContainer pulls all images when not tag is specified
I recently update the version to 1.15.0 due to #3166, and I found that when I use `DockerComposeContainer` + `Dockerfile` with a `FROM` directive w/o tag, testcontainers tries to pull all images (didn't wait for that happens, just saw it pulls several ancient images, see picture below).

### Steps to Reproduce

Remove all `openresty/openresty` images locally

#### `docker-compose.yml`

```yaml
version: '2.1'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    entrypoint: [ 'bash', '-c', 'sleep 5 && /usr/bin/openresty -c /var/nginx/conf.d/nginx.conf' ]

```

#### `Dockerfile.nginx`

```Dockerfile
FROM openresty/openresty

RUN echo 'whatever'
```

#### Test codes

```java
import java.io.File;
import org.junit.Test;
import org.testcontainers.containers.DockerComposeContainer;

public class Reproduce {
    @Test
    public void reproduce() {
        final DockerComposeContainer compose = new DockerComposeContainer(new File("src/test/java/docker-compose.yml"));
        compose.start();
    }
}
```

Run the test codes, the logs keep printing something like this:

image

and `docker images` shows that it is pulling all images:

```shell
$ docker images | grep openresty
openresty/openresty    1.17.8.2-5-alpine-fat                            5a1867b4dc55        7 weeks ago         353MB
openresty/openresty    1.11.2.1-alpine                                  590e643a8136        4 years ago         44MB
openresty/openresty    1.11.2.1-centos                                  f43d744951d5        4 years ago         374MB
openresty/openresty    1.11.2.1-centos-rpm                              dfbc7fc2ba3f        4 years ago         226MB
```

it pulled images **4 years ago**, I'm expecting it only pulls the image with tag `latest` by default, like what it did before upgrading to 1.15.0.

Now I work around this by specifying the tag explicitly:

```Dockerfile
FROM openresty/openresty:1.17.8.2-5-alpine-fat
```

This may be a bug in 1.15.0? @rnorth @bsideup

### PR DESCRIPTION
**Pull request by rnorth**
Fixes #3442﻿

### CODE REVIEW

**Comment by rnorth** [comment]
I believe this is likely to help with some of our long CI times - particularly the Windows CI job which has been timing out quite regularly of late.

**Review by kiview — APPROVED** [review]
LGTM

File: core/src/main/java/org/testcontainers/containers/DockerComposeFiles.java [hunk 1]
```diff
@@ -1,43 +1,43 @@
...
 
     private Set<String> getImageNames(Map<String, Set<String>> serviceToImageNames) {
-        Set<String> imageNames = new HashSet<>();
-        serviceToImageNames.values().stream().forEach(imageNames::addAll);
-        return imageNames;
+        return serviceToImageNames.values().stream()
+            .flatMap(Collection::stream)
+            // Pass through DockerImageName to convert image names to canonical form (e.g. making implicit latest tag explicit)
+            .map(DockerImageName::parse)
+            .map(DockerImageName::asCanonicalNameString)
```
Comment (rnorth) [inline core/src/main/java/org/testcontainers/containers/DockerComposeFiles.java:40]: FWIW this is the substance of the change; everything else is just tidying of the existing code.

**Review by bsideup — APPROVED** [review]
