### PR TITLE
Fail fast if `container_name` is set in Docker Compose file

### LINKED ISSUE #1151: docker-compose entry container_name not supported
I just tried to run a `DockerComposeContainer` with a docker-compose file that contained `container_name` entries. Running it just fails like this:

```
22:33:13.389 [main] INFO  🐳 [alpine/socat:latest] - Creating container for image: alpine/socat:latest
22:33:13.545 [main] ERROR 🐳 [alpine/socat:latest] - Could not start container
org.testcontainers.containers.ContainerLaunchException: Aborting attempt to link to container zhq16mnbjgg6_api_1 as it is not running
    at org.testcontainers.containers.GenericContainer.applyConfiguration(GenericContainer.java:477)
    at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:232)
    at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:216)
    at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:76)
    at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:214)
    at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:203)
    at org.testcontainers.containers.DockerComposeContainer.startAmbassadorContainers(DockerComposeContainer.java:242)
    at org.testcontainers.containers.DockerComposeContainer.start(DockerComposeContainer.java:153)
    at com.brandwatch.integrationtests.testhelpers.DockerComposeEnvironment.start(DockerComposeEnvironment.java:80)
    at com.brandwatch.integrationtests.testhelpers.DockerComposeEnvironment.<init>(DockerComposeEnvironment.java:64)
    at com.brandwatch.integrationtests.testhelpers.DockerComposeEnvironment.<clinit>(DockerComposeEnvironment.java:29)
    at com.brandwatch.integrationtests.SignalControllerIT.<clinit>(SignalControllerIT.java:40)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
    at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runners.Suite.runChild(Suite.java:128)
    at org.junit.runners.Suite.runChild(Suite.java:27)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
    at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
    at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
    at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
    at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
    at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:159)
    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
    at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
```

I could imagine that in parts `container_name` is ignored, in parts it isn't, which leads to the container being referenced to as `zhq16mnbjgg6_api_1` in some parts, and as `api` (the `container_name`) in other parts. This might lead to this error, although I haven't checked.

This same issue was raised before:
https://github.com/testcontainers/testcontainers-java/issues/265#issuecomment-272618508

It would help if testcontainers would either add proper support for this, or fail fast with a useful error message saying that this field is not supported.

### PR DESCRIPTION
**Pull request by bsideup**
Fixes #1151. Submitting a new one since #1432 was closed by the author.

### CODE REVIEW

File: core/src/test/java/org/testcontainers/containers/DockerComposeFileValidationTest.java [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+                    "services", ImmutableMap.of(
+                        "redis", ImmutableMap.of("container_name", "redis")
+                    )
+                ), "");
+            })
+            .hasMessageContaining("'container_name' property set for service 'redis'");
+    }
+
+    @Test
+    public void shouldIgnoreUnknownStructure() {
```
Comment (kiview) [inline core/src/test/java/org/testcontainers/containers/DockerComposeFileValidationTest.java]: Why?
For possible forward compatibility?

File: core/src/main/java/org/testcontainers/containers/DockerComposeContainer.java [hunk 2]
```diff
@@ -211,6 +224,59 @@ private void runWithCompose(String cmd) {
...
+            servicesMap = (Map<String, ?>) services;
+        } else {
+            servicesMap = map;
+        }
+
+        for (Map.Entry<String, ?> entry : servicesMap.entrySet()) {
+            String serviceName = entry.getKey();
+            Object serviceDefinition = entry.getValue();
+            if (!(serviceDefinition instanceof Map)) {
+                break;
```
Comment (rnorth) [inline core/src/main/java/org/testcontainers/containers/DockerComposeContainer.java]: Do we `break` rather than `continue` just to abort validation entirely?

File: core/build.gradle [hunk 3]
```diff
@@ -92,6 +92,8 @@ dependencies {
         exclude(group: 'org.apache.commons', module: 'commons-compress')
     }
 
+    shaded "org.yaml:snakeyaml:1.21"
```
Comment (rnorth) [inline core/build.gradle]: Not a big deal, but we already have Jackson on the classpath. Did we consider using that instead of SnakeYAML?

File: core/src/test/java/org/testcontainers/containers/DockerComposeFileValidationTest.java [hunk 4]
```diff
@@ -0,0 +1,70 @@
...
+        // Everything is a list
+        DockerComposeContainer.validate(emptyList(), "");
+
+        // services is not a map but List
+        DockerComposeContainer.validate(ImmutableMap.of(
+            "version", "2",
+            "services", emptyList()
+        ), "");
+
+        // services is not a collection
```
Comment (rnorth) [inline core/src/test/java/org/testcontainers/containers/DockerComposeFileValidationTest.java]:
```suggestion
        // services is not a map
```

File: core/build.gradle (hunk 3 above)
Comment (bsideup) [reply core/build.gradle]: Jackson does not support YAML. There is YAML module for Jackson that uses SnakeYAML internally :)

File: core/src/test/java/org/testcontainers/containers/DockerComposeFileValidationTest.java (hunk 4 above)
Comment (bsideup) [reply core/src/test/java/org/testcontainers/containers/DockerComposeFileValidationTest.java]: "is not a map" is checked before this one. We check for "not a collection" because a mapper may pass on collection type, but fail on non-collection one, that was my assumption :)

File: core/src/main/java/org/testcontainers/containers/DockerComposeContainer.java (hunk 2 above)
Comment (bsideup) [reply core/src/main/java/org/testcontainers/containers/DockerComposeContainer.java]: Will do 👍

File: core/src/main/java/org/testcontainers/containers/DockerComposeContainer.java [hunk 5]
```diff
@@ -211,6 +224,59 @@ private void runWithCompose(String cmd) {
...
+            Object template = yaml.load(fileInputStream);
+            validate(template, composeFile.getAbsolutePath());
+        } catch (IOException e) {
+            log.warn("Failed to read YAML from {}", composeFile.getAbsolutePath(), e);
+        }
+    }
+
+    @VisibleForTesting
+    static void validate(Object template, String identifier) {
+        if (!(template instanceof Map)) {
```
Comment (kiview) [inline core/src/main/java/org/testcontainers/containers/DockerComposeContainer.java]: I think we could extract 240-261 into a private function and then have 
```
if (!hasKnownFormat(object)) {
  log.debug("Compose file {} has an unknown format", identifier);
  return
}
...
```

File: core/src/main/java/org/testcontainers/containers/DockerComposeContainer.java [hunk 6]
```diff
@@ -211,6 +224,59 @@ private void runWithCompose(String cmd) {
...
+                log.debug("Compose file {} has an unknown format: 'services' is not Map", identifier);
+                return;
+            }
+
+            servicesMap = (Map<String, ?>) services;
+        } else {
+            servicesMap = map;
+        }
+
+        for (Map.Entry<String, ?> entry : servicesMap.entrySet()) {
```
Comment (kiview) [inline core/src/main/java/org/testcontainers/containers/DockerComposeContainer.java]:
```
for (Map.Entry<String, ?> entry : servicesMap.entrySet()) {
  validateEntry(entry)
}
```
Just an idea?
We can't break in this case of course.

File: core/src/test/java/org/testcontainers/containers/DockerComposeFileValidationTest.java (hunk 1 above)
Comment (bsideup) [reply core/src/test/java/org/testcontainers/containers/DockerComposeFileValidationTest.java]: Yes. We should rather do "best effort" detection rather then making it fail on parsing

File: core/src/main/java/org/testcontainers/containers/DockerComposeContainer.java (hunk 5 above)
Comment (bsideup) [reply core/src/main/java/org/testcontainers/containers/DockerComposeContainer.java]: extracted methods make it much harder to follow the structure IMO, especially when dealing with the format/structure validation

Comment (kiview) [reply core/src/main/java/org/testcontainers/containers/DockerComposeContainer.java]: I disagree, since it makes the responsibility of the part of the code clearer (therefore also increasing maintainability).
But we don't need to fight over this :wink:

File: core/build.gradle (hunk 3 above)
Comment (rnorth) [reply core/build.gradle]: I wasn't aware that it used SnakeYAML! OK, makes sense!
