### PR TITLE
ConnectionWrapper#rollback(Savepoint) delegates to wrong method #1909

### LINKED ISSUE #1909: ConnectionWrapper#rollback(Savepoint) delegates to wrong method
`ConnectionWrapper#rollback(Savepoint)` delegates to `Connection#rollback()` instead of `Connection#rollback(Savepoint)`: https://github.com/testcontainers/testcontainers-java/blob/b6a5248365acb240cd6f6c7d3c1ae38c6c5b3ed7/modules/jdbc/src/main/java/org/testcontainers/jdbc/ConnectionWrapper.java#L165-L168

### PR DESCRIPTION
**Pull request by MariuszCwikla**
Fixes #1909

### CODE REVIEW

**Comment by bsideup** [comment]
Hi @MariuszCwikla,

As discussed in the issue ( https://github.com/testcontainers/testcontainers-java/issues/1909#issuecomment-537009872 ), @thiyagu-7 wanted to submit a fix for this one, since it was up for grabs.

I suggest we wait one day and if he did not, we will merge yours as it seems to be the exact fix for the issue and follows the guideline.

We do this to respect first responders, but appreciate your time you spend submitting the PR!
Or maybe @thiyagu-7 will agree to merge yours instead :)

File: modules/jdbc/src/main/java/org/testcontainers/jdbc/ConnectionDelegate.java [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+import java.sql.*;
+import java.util.Map;
+import java.util.Properties;
+import java.util.concurrent.Executor;
+
+class ConnectionDelegate implements Connection {
+    @Delegate(types=Connection.class)
+    private final Connection delegate;
+
+    public ConnectionDelegate(Connection connection){
```
Comment (bsideup) [inline modules/jdbc/src/main/java/org/testcontainers/jdbc/ConnectionDelegate.java]: nit: you could add `@Value` on the class and remove the constructor and `private final` from the variable declaration

File: modules/jdbc/src/main/java/org/testcontainers/jdbc/ConnectionDelegate.java [hunk 2]
```diff
@@ -0,0 +1,18 @@
...
+import lombok.Data;
+import lombok.experimental.Delegate;
+
+import java.sql.*;
+import java.util.Map;
+import java.util.Properties;
+import java.util.concurrent.Executor;
+
+class ConnectionDelegate implements Connection {
+    @Delegate(types=Connection.class)
```
Comment (bsideup) [inline modules/jdbc/src/main/java/org/testcontainers/jdbc/ConnectionDelegate.java]: nit: `types` here is unnecessary because it uses the variable's type, which equals to `Connection` already

File: modules/jdbc/src/main/java/org/testcontainers/jdbc/ConnectionWrapper.java [hunk 3]
```diff
@@ -1,294 +1,24 @@
...
-        delegate.commit();
-    }
+    private final Runnable closeCallback;
 
-    @Override
-    public void rollback() throws SQLException {
-        delegate.rollback();
+    public ConnectionWrapper(Connection connection, Runnable runnable) {
+        super(connection);
+        this.closeCallback =runnable;
```
Comment (bsideup) [inline modules/jdbc/src/main/java/org/testcontainers/jdbc/ConnectionWrapper.java]:
```suggestion
        this.closeCallback = runnable;
```

File: modules/jdbc/src/main/java/org/testcontainers/jdbc/ConnectionWrapper.java [hunk 4]
```diff
@@ -1,294 +1,24 @@
...
 
     @Override
     public void close() throws SQLException {
-        delegate.close();
+        super.close();
         try {
-            this.closeCallback.run();
-        } catch (Exception e) {
+            closeCallback.run();
+        }catch(Exception e){
```
Comment (bsideup) [inline modules/jdbc/src/main/java/org/testcontainers/jdbc/ConnectionWrapper.java]:
```suggestion
        } catch(Exception e) {
```

File: modules/jdbc/src/main/java/org/testcontainers/jdbc/ConnectionDelegate.java (hunk 1 above)
Comment (MariuszCwikla) [reply modules/jdbc/src/main/java/org/testcontainers/jdbc/ConnectionDelegate.java]: `@Value` will not work - it makes class final which prevents from inheriting (see `ConnectionWrapper`)
But `@AllArgsConstructor` will work instead

Comment (bsideup) [reply modules/jdbc/src/main/java/org/testcontainers/jdbc/ConnectionDelegate.java]: Right 👍

**Comment by thiyagu-7** [comment]
@bsideup I'm happy to let you merge @MariuszCwikla's changes.

**Comment by bsideup** [comment]
thanks @thiyagu-7!

File: modules/jdbc/src/main/java/org/testcontainers/jdbc/ConnectionWrapper.java (hunk 4 above)
Comment (MariuszCwikla) [reply modules/jdbc/src/main/java/org/testcontainers/jdbc/ConnectionWrapper.java]: done, thx

File: modules/jdbc/src/main/java/org/testcontainers/jdbc/ConnectionWrapper.java (hunk 3 above)
Comment (MariuszCwikla) [reply modules/jdbc/src/main/java/org/testcontainers/jdbc/ConnectionWrapper.java]: done, thx

File: modules/jdbc/src/main/java/org/testcontainers/jdbc/ConnectionDelegate.java (hunk 2 above)
Comment (MariuszCwikla) [reply modules/jdbc/src/main/java/org/testcontainers/jdbc/ConnectionDelegate.java]: done, thx

**Comment by bsideup** [comment]
@MariuszCwikla I applied a small fix and will merge once CI is green 🎉 👍

**Comment by bsideup** [comment]
@MariuszCwikla merged, thanks! 👍
