### PR TITLE
Un-shade docker-java-api

### LINKED ISSUE #1113: com.github.docker-java is not shaded and conflicts with the project's version
Adding com.github.docker-java:docker-java to a project that uses testcontainers creates dependency conflicts. In a way this issue is related to [this one](https://github.com/testcontainers/testcontainers-java/issues/35) but that one is closed.

This example with the below dependencies demonstrate the problem
```
import org.junit.Test;
import org.testcontainers.containers.MySQLContainer;

public class DockerJavaTest {
    @Test
    public void dockerJavaTest() {
        MySQLContainer mySQLContainer = new MySQLContainer();
        mySQLContainer.start();
        mySQLContainer.stop();
    }
}
```

```
plugins {
    id 'java'
}

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    testCompile 'com.github.docker-java:docker-java:3.0.6'
    testCompile "org.testcontainers:testcontainers:1.10.4"
    testCompile "org.testcontainers:mysql:1.10.4"
    testCompile "ch.qos.logback:logback-classic:1.2.2"
    testCompile group: 'junit', name: 'junit', version: '4.12'
}
```

```
org.testcontainers.shaded.com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "ID" (class com.github.dockerjava.api.model.Info), not marked as ignorable (48 known properties: "systemStatus", "ipv4Forwarding", "httpsProxy", "discoveryBackend", "httpProxy", "clusterStore", "cpuCfsPeriod", "dockerRootDir", "containersRunning", "operatingSystem", "containers", "architecture", "initPath", "cpuSet", "containersStopped", "systemTime", "oomKillDisable", "registryConfig", "containersPaused", "oomScoreAdj", "experimentalBuild", "loggingDriver", "driver", "nfd", "noProxy", "memTotal", "cpuCfsQuota", "bridgeNfIp6tables", "initSha1", "images", "memoryLimit", "cpuShares", "osType", "indexServerAddress", "name", "bridgeNfIptables", "debug", "serverVersion", "id", "plugins", "driverStatuses", "ncpu", "labels", "executionDriver", "kernelVersion", "sockets", "swapLimit", "clusterAdvertise"])
 at [Source: buffer(org.testcontainers.shaded.okhttp3.internal.http1.Http1Codec$ChunkedSource@4f209819).inputStream(); line: 1, column: 8] (through reference chain: com.github.dockerjava.api.model.Info["ID"])

	at org.testcontainers.shaded.com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:51)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:839)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1045)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1352)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1330)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:264)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2803)
	at org.testcontainers.dockerclient.transport.okhttp.OkHttpInvocationBuilder.get(OkHttpInvocationBuilder.java:101)
	at com.github.dockerjava.core.exec.InfoCmdExec.exec(InfoCmdExec.java:24)
	at com.github.dockerjava.core.exec.InfoCmdExec.exec(InfoCmdExec.java:14)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:112)
	at org.testcontainers.containers.GenericContainer.<init>(GenericContainer.java:162)
	at org.testcontainers.containers.JdbcDatabaseContainer.<init>(JdbcDatabaseContainer.java:40)
	at org.testcontainers.containers.MySQLContainer.<init>(MySQLContainer.java:24)
	at DockerJavaTest.dockerJavaTest(DockerJavaTest.java:8)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

### PR DESCRIPTION
**Pull request by bsideup**
This PR makes Testcontainers _depend_ on `docker-java-api` instead of including it into our JAR unshaded. Note that `docker-java-core` and `docker-java-transport-okhttp` remain shaded due to their transitive dependencies like Guava or now-in-Kotlin OkHttp.

The transition requires a breaking change in the `DockerClientProviderStrategy` API and includes a rework.
The rework also includes an improvement that removes one Docker API call (`/_ping`) and instead reuses the `/_info` one (reduces the startup by ~200ms).

The dependency graph now looks like this:
Screenshot 2020-06-16 at 11 26 23 AM

While previously it was:
Screenshot 2020-06-16 at 11 56 32 AM

Fixes #1113

### CODE REVIEW

File: core/src/main/java/org/testcontainers/images/TimeLimitedLoggedPullImageResultCallback.java [hunk 1]
```diff
@@ -19,7 +18,7 @@
 import static org.testcontainers.DockerClientFactory.TESTCONTAINERS_THREAD_GROUP;
 
 /**
- * {@link PullImageResultCallback} with improved logging of pull progress and a 'watchdog' which will abort the pull
+ * {@link LoggedPullImageResultCallback} with improved logging of pull progress and a 'watchdog' which will abort the pull
```
Comment (rnorth) [inline core/src/main/java/org/testcontainers/images/TimeLimitedLoggedPullImageResultCallback.java:21]: Not a big deal, but I'd query this change..

Comment (rnorth) [reply core/src/main/java/org/testcontainers/images/TimeLimitedLoggedPullImageResultCallback.java:21]: Shouldn't this instead be a reference to `com.github.dockerjava.api.command.PullImageResultCallback`, which is the root-iest subclass that this class is a specialisation of?

From the perspective of someone looking at the public APIs, `LoggedPullImageResultCallback` doesn't exist.

Comment (bsideup) [reply core/src/main/java/org/testcontainers/images/TimeLimitedLoggedPullImageResultCallback.java:21]: @rnorth I wanted to avoid referencing 3rd party classes at all, but don't mind changing it to `PullImageResultCallback` :)

**Comment by dagguh** [comment]
> Note that docker-java-core and docker-java-transport-okhttp remain shaded due to their transitive dependencies like Guava or now-in-Kotlin OkHttp.

Any plans to unshade it all? I'm still getting nasty classpath clashes:
```
    java.lang.NoSuchMethodError: com.github.dockerjava.core.DockerClientConfig.getObjectMapper()Lorg/testcontainers/shaded/com/fasterxml/jackson/databind/ObjectMapper;
        at com.github.dockerjava.okhttp.OkHttpDockerCmdExecFactory.init(OkHttpDockerCmdExecFactory.java:124)
        at com.github.dockerjava.core.DockerClientImpl.withDockerCmdExecFactory(DockerClientImpl.java:242)
        at org.testcontainers.dockerclient.DockerClientProviderStrategy.getClientForConfig(DockerClientProviderStrategy.java:177)
        at org.testcontainers.dockerclient.UnixSocketClientProviderStrategy.tryConfiguration(UnixSocketClientProviderStrategy.java:62)
        at org.testcontainers.dockerclient.UnixSocketClientProviderStrategy.test(UnixSocketClientProviderStrategy.java:36)
        at org.testcontainers.dockerclient.DockerClientProviderStrategy.lambda$getFirstValidStrategy$2(DockerClientProviderStrategy.java:118)
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
        at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:302)
        at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:728)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:469)
        at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:154)
        at org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:126)
        at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:147)
```
