### PR TITLE
Check container's status if `WaitStrategy` fails.

### LINKED ISSUE #1834: If WaitStrategy fails, we should log if the container is still running or failed
If container fails to start for some reason (e.g. OOM), wait strategy will fail, but the message won't indicate whether the container is running but fails to respond on the given host:port or it crashed

### PR DESCRIPTION
**Pull request by bsideup**
Fixes #1834

### CODE REVIEW

File: core/src/main/java/org/testcontainers/containers/GenericContainer.java [hunk 1]
```diff
@@ -329,11 +331,51 @@ private void tryStart() {
...
+                    throw new IllegalStateException("Container exited with code " + state.getExitCode());
+                }
+
+                throw e;
+            }
 
             logger().info("Container {} started", dockerImageName);
             containerIsStarted(containerInfo);
         } catch (Exception e) {
+            if (e instanceof UndeclaredThrowableException && e.getCause() instanceof Exception) {
```
Comment (bsideup) [inline core/src/main/java/org/testcontainers/containers/GenericContainer.java]: slightly unrelated change but since I was getting a lot of errors while debugging, I could not notice that the logs contained **double** wrapped exceptions

File: core/src/main/java/org/testcontainers/containers/GenericContainer.java [hunk 2]
```diff
@@ -329,11 +331,51 @@ private void tryStart() {
...
+                    throw new IllegalStateException("Container is removed");
+                }
+
+                InspectContainerResponse.ContainerState state = inspectContainerResponse.getState();
+                if (Boolean.TRUE.equals(state.getDead())) {
+                    throw new IllegalStateException("Container is dead");
+                }
+
+                if (Boolean.TRUE.equals(state.getOOMKilled())) {
+                    throw new IllegalStateException("Container crashed with out-of-memory");
```
Comment (rnorth) [inline core/src/main/java/org/testcontainers/containers/GenericContainer.java]: Super trivial, but could we include the string `OOMKilled` in the message? i.e.

```suggestion
                    throw new IllegalStateException("Container crashed with out-of-memory (OOMKilled)");
```

`OOMKilled` as a term has become fairly standard, with a specific meaning, so I think it's better to keep the specificity of the error as we propagate it.

File: core/src/main/java/org/testcontainers/containers/GenericContainer.java (hunk 1 above)
Comment (rnorth) [reply core/src/main/java/org/testcontainers/containers/GenericContainer.java]: Interesting... Good spot.

File: core/src/test/java/org/testcontainers/containers/GenericContainerTest.java [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+
+    @Test
+    public void shouldReportOOMAfterWait() {
+        try (
+            GenericContainer container = new GenericContainer<>()
+                .waitingFor(new WaitForState(ContainerState::getOOMKilled))
+                .withCreateContainerCmdModifier(it -> {
+                    it.getHostConfig().withMemory(4 * FileUtils.ONE_MB);
+                })
+                .withCommand("sh", "-c", "usleep 100; dd if=/dev/urandom bs=128GB count=1 > test.txt")
```
Comment (rnorth) [inline core/src/test/java/org/testcontainers/containers/GenericContainerTest.java]: Gulp... Better get this right 😅 😂 

At first sight I was perplexed as to why writing to disk would cause OOMKill at all, but realised that actually the only thing that matters here is having the blocksize be >4MB, as dd buffers into memory before writing.

If that's the case, could we use `> /dev/null` or `of=/dev/null` to just be explicit about blackholing the data?

This might be slightly less alarming for anyone reading the code in future who fears we're about to fill their disk with garbage 😄.

**Comment by rnorth** [comment]
Ohoh, build is failing. Looks like we're not getting OOMKilled like we want to.

**Comment by bsideup** [comment]
@rnorth yeah, will try to debug it (works locally)

**Comment by rnorth** [comment]
Trying to diagnose why this org.testcontainers.containers.GenericContainerTest test is behaving strangely
